### ISSUE TITLE
Don't magically increase room temperature

### ISSUE THREAD

**Issue by perkinslr** [Ratysz/RT_SolarFlareShield#14]
Line 96 in CompRTSolarFlareShield.cs increases the room group temperature, which doesn't play properly with other mods which affect temperature stuff.

The proper solution is to use 

    GenTemperature.PushHeat(parent.Position, parent.Map, properties.heatingPerTick * tickAmount);

Which routes the heat pushing through the same mechanism as fires, heaters, and the like.

**Comment by perkinslr** [comment]
Note that the second check on line 94 can also be elided, as PushHeat will filter out outdoor room groups from having their temperature adjusted.

**Comment by Ratysz** [comment]
Fixed, thank you.
