### ISSUE TITLE
Investigate EMI dynamo interaction

### ISSUE THREAD

**Issue by Ratysz** [Ratysz/RT_SolarFlareShield#15]
From `Winter`:
> Had a mechanoid cluster drop in today (not sure if that's Royalty DLC or vanilla), with an EMI dynamo. It creates an EMI field, which I think is supposed to shut down everything that runs on power. My flare shield was only consuming the usual 50 watts, but all my colony's powered systems stayed active. Just to test, I toggled the shield's power off, and the EMI field shut everything else down.

**Comment by Stifling-Bossness** [comment]
Just want to add that you can also be under the effect of an EMI field from another royalty quest, which pays you to withstand it for a period of time.
