### ISSUE TITLE
Credit duduluu with their translations!

### ISSUE THREAD

**Issue by Ratysz** [Ratysz/RT_SolarFlareShield#2]
This is just disgraceful.

**Comment by duduluu** [comment]
Uh, what does disgraceful mean?

**Comment by Ratysz** [comment]
It means that I should be ashamed of forgetting to credit you with the translations in the mod's description. I've put this issue up to remind myself to fix that in the next update.

**Comment by duduluu** [comment]
Don't mind.
Chinese players know, because of our team websit.
http://rimworldzh.huiji.wiki/wiki/Mod/Ratysz

**Comment by Ratysz** [comment]
Fixed with 6a118d7f8d793d7fa5a8aba1716f759d33b3669d
